server:
  port: 8088

spring:
  application:
    name: user-service
  profiles:
    active: dev,db

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka #单机版


logging:
  level:
    com.alsritter: info