server:
  port: 8010

spring:
  application:
    name: gateway
  main:
    # 允许通过注册与现有定义同名的定义来覆盖 bean 定义。
    allow-bean-definition-overriding: true
# 设置日志级别
logging:
  level:
    org.springframework: info
    com.alsritter: debug
