server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka #单机版

spring:
  application:
    name: "gateway-service"


  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true                             #开启从注册中心动态创建路由的功能
          lower-case-service-id: true               #使用小写服务名，默认是大写
      routes: # 可以配置多个路由
        - id: user                                  # 路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://user-service                    # 这里填写服务注册的时用的名字
          predicates:
            - Path=/user/**                         # 断言，路径相匹配的进行路由（后面的 ** 通配符可以用来匹配 PathVariable）
          filters:
            - StripPrefix=1
        - id: oauth2
          uri: lb://oauth2-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1