server:
  port: 19999

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: "gateway-service"
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（ms）
    timeout: 10000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  #  # 注意：别忘了设置缓存用的是 redis
  #  cache:
  #    type: redis
  #

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    loadbalancer:
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true                             #开启从注册中心动态创建路由的功能
          lower-case-service-id: true               #使用小写服务名，默认是大写
      routes: # 可以配置多个路由
        - id: user                                  # 路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://user-service                    # 这里填写服务注册的时用的名字
          predicates:
            - Path=/user/**                         # 断言，路径相匹配的进行路由（后面的 ** 通配符可以用来匹配 PathVariable）
          filters:
            - StripPrefix=1
        - id: oauth2
          uri: lb://oauth2-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: forum
          uri: lb://forum-service
          predicates:
            - Path=/forum/**
          filters:
            - StripPrefix=1


secure:
  config:
    client-id: webClient
    client-secret: secret
#    位置 org.springframework.security.oauth2.provider.endpoint
    # 这里完整的地址是 http://127.0.0.1:19999/auth/oauth/check_token 就是自己
    check-token-endpoint-url: /auth/oauth/check_token
  ignore:
    urls: #配置白名单路径
      - "/auth/**"
      - "/forum/auth/**"

logging:
  level:
    com.alsritter: debug