server:
  port: 7088

spring:
  application:
    name: test-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.alsritter: info