server:
  port: 8088
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-service

rsa:
  key:
    pubKeyPath: "classpath:rsa/id_key_rsa.pub"
    priKeyPath: "classpath:rsa/id_key_rsa"
