spring:
  application:
    name: eureka

server:
  port: 8000 #启动端口

eureka:
  server:
    enable-self-preservation: false      #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 10000 #清理间隔（单位毫秒，默认是 60 * 1000）5秒将客户端剔除的服务在服务注册列表中剔除
  client:
    register-with-eureka: false   # false:不作为一个客户端注册到注册中心
    fetch-registry: false         #为 true 的话就是拉取远程的其它的注册中心
    instance-info-replication-interval-seconds: 10
    serviceUrl:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
